#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-lpSolve
Version  : 5.6.19
Release  : 55
URL      : https://cran.r-project.org/src/contrib/lpSolve_5.6.19.tar.gz
Source0  : https://cran.r-project.org/src/contrib/lpSolve_5.6.19.tar.gz
Summary  : Interface to 'Lp_solve' v. 5.5 to Solve Linear/Integer Programs
Group    : Development/Tools
License  : LGPL-2.0
Requires: R-lpSolve-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
solving linear, integer and mixed integer programs. In this
        implementation we supply a "wrapper" function in C and some R
        functions that solve general linear/integer problems,
        assignment problems, and transportation problems. This version
        calls lp_solve version 5.5.

%package lib
Summary: lib components for the R-lpSolve package.
Group: Libraries

%description lib
lib components for the R-lpSolve package.


%prep
%setup -q -n lpSolve
pushd ..
cp -a lpSolve buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1694624654

%install
export SOURCE_DATE_EPOCH=1694624654
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/lpSolve/DESCRIPTION
/usr/lib64/R/library/lpSolve/INDEX
/usr/lib64/R/library/lpSolve/Meta/Rd.rds
/usr/lib64/R/library/lpSolve/Meta/features.rds
/usr/lib64/R/library/lpSolve/Meta/hsearch.rds
/usr/lib64/R/library/lpSolve/Meta/links.rds
/usr/lib64/R/library/lpSolve/Meta/nsInfo.rds
/usr/lib64/R/library/lpSolve/Meta/package.rds
/usr/lib64/R/library/lpSolve/NAMESPACE
/usr/lib64/R/library/lpSolve/R/lpSolve
/usr/lib64/R/library/lpSolve/R/lpSolve.rdb
/usr/lib64/R/library/lpSolve/R/lpSolve.rdx
/usr/lib64/R/library/lpSolve/help/AnIndex
/usr/lib64/R/library/lpSolve/help/aliases.rds
/usr/lib64/R/library/lpSolve/help/lpSolve.rdb
/usr/lib64/R/library/lpSolve/help/lpSolve.rdx
/usr/lib64/R/library/lpSolve/help/paths.rds
/usr/lib64/R/library/lpSolve/html/00Index.html
/usr/lib64/R/library/lpSolve/html/R.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/lpSolve/libs/lpSolve.so
/usr/lib64/R/library/lpSolve/libs/lpSolve.so.avx2
/usr/lib64/R/library/lpSolve/libs/lpSolve.so.avx512
